import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const commit = "0fe0da905053588627146e7f037457a64285a93c";
const repositoryUrl = "https://github.com/kokubunken/kokusho-itaiji-search";
const sourceUrl = `https://raw.githubusercontent.com/kokubunken/kokusho-itaiji-search/${commit}/kokusho_itaiji.sql`;
const input = process.argv[2];
const output = resolve("src/lib/kokusho-itaiji-data.ts");

const sql = input
  ? await readFile(resolve(input), "utf8")
  : await fetch(sourceUrl).then((response) => {
      if (!response.ok) throw new Error(`異体字SQLを取得できませんでした（HTTP ${response.status}）`);
      return response.text();
    });

const insertPattern = /^INSERT INTO synonyms VALUES \('((?:''|[^'])*)', '((?:''|[^'])*)'\);$/gm;
const pairs = [...sql.matchAll(insertPattern)].map(([, target, normalized]) => [
  target.replaceAll("''", "'"),
  normalized.replaceAll("''", "'"),
]);

if (pairs.length < 1000) {
  throw new Error(`異体字データが不足しています（${pairs.length}件）。SQL形式を確認してください。`);
}

const grouped = new Map();
for (const [target, normalized] of pairs) {
  const variants = grouped.get(normalized) ?? [];
  if (!variants.includes(target)) variants.push(target);
  grouped.set(normalized, variants);
}

const entries = [...grouped].map((entry) => `  ${JSON.stringify(entry)},`).join("\n");
const generated = `// Generated by scripts/update-itaiji.mjs. Do not edit manually.
export const KOKUSHO_ITAIJI_SOURCE = ${JSON.stringify(repositoryUrl)};
export const KOKUSHO_ITAIJI_COMMIT = ${JSON.stringify(commit)};
export const KOKUSHO_ITAIJI_PAIR_COUNT = ${pairs.length};
export const KOKUSHO_ITAIJI_ENTRIES = [
${entries}
] as const;
`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, "utf8");
console.log(`Generated ${grouped.size} groups from ${pairs.length} pairs at ${output}`);
